// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import astro from 'eslint-plugin-astro';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import tailwind from 'eslint-plugin-tailwindcss';

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...astro.configs.recommended,
  ...tailwind.configs['flat/recommended'],
  {
    settings: {
      tailwindcss: {
        // Allow intentional component class names managed by JavaScript
        whitelist: [
          'active',
          'back',
          'back-btn',
          'back-link',
          'badge',
          'badge-float',
          'canvas-wrapper',
          'code-container',
          'cta',
          'cta-link',
          'cta-primary',
          'description',
          'diagram-container',
          'diagram-wrapper',
          'dot',
          'example-btn',
          'examples',
          'excalidraw-view',
          'feature-card',
          'feature-grid',
          'feature-item',
          'feature-item-body',
          'feature-item-desc',
          'feature-item-icon',
          'feature-item-title',
          'feature-list',
          'feature-section',
          'features-link',
          'fs-icon',
          'fs-label',
          'future',
          'github-link',
          'hint',
          'mermaid',
          'mermaid-view',
          'mermaid-wrapper',
          'nav-btn',
          'page-content',
          'past',
          'positions-container',
          'present',
          'progress-dots',
          'renderer-btn',
          'renderer-toggle',
          'reveal',
          'section-heading',
          'section-icon',
          'section-title',
          'slide',
          'slide-badge',
          'slide-body',
          'slide-counter',
          'slide-nav',
          'slide-nav-controls',
          'slide-subtitle',
          'slide-title',
          'slides',
          'swagger-wrapper',
          'tab-btn',
          'tab-panel',
          'tabs',
          'title-glow',
          'view-btn',
          'view-toggle',
          'zoom-btn',
          'zoom-controls',
          'zoom-hint',
        ],
      },
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      react,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
];
